version: "3.7"
services:
    api:
        container_name: template_nest
        image: template_nest
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile.local
        restart: always
        volumes:
            - ./src:/template_nest/src
        ports:
            - "3000:3000"
